export const ISO_PURPOSE_CODES = [
    "ACCT","ADCS","ADVA","AGRT","ALLW","ALMY","AREN","BBSC","BECH","BENE",
    "BEXP","BOCE","BONU","CASH","CFEE","CHAR","COLL","COMC","COMM","COMP",
    "COMT","CORT","COST","CPYR","CSDB","DBTC","DEBT","DEPD","DEPT","EDUC",
    "EPAY","ESTX","FEES","FWLV","GAFA","GAHO","GDDS","GDSV","GIFT","GOVT",
    "GSCB","GSTX","GVEA","HSTX","IHRP","INSM","INTC","INTE","INTP","INTX",
    "IPAY","IPCA","IPDO","IPEA","IPEC","IPEW","IPPS","IPRT","IVPT","LICF",
    "LIMA","LOAN","LOAR","MP2B","MP2P","MSVC","NETT","NITX","NOWS","OFEE",
    "OTHR","PADD","PAYR","PEFC","PENS","POPE","PRCP","PTSP","PTXP","RAPI",
    "RCKE","RCPT","RDTX","REBT","REFU","REOD","RETL","RHBS","RIMB","RINP",
    "ROYA","RRCT","RRTP","SALA","SAVG","SCVE","SERV","SPSP","SSBE","STDY",
    "SUBS","SUPP","TAXR","TAXS","TCSC","TRAD","TRFD","VATX","WEBI","WHLD"
];
