# LambdaTest Configuration

# Project and folder configuration
project_id: "01KPB5KRH09TR87X76WMA6MS9F"
folder_id: "01KPB5KRHPJQJWRZW0SSGEPK63"

# Test Run configuration
assignee: 3254070
environment_id: 258739

# Test URL for automation
test_url: "https://demo.lambdatestinternal.com"
